### PR TITLE
[WIP][MIG] connector_woocommerce: Migration to 12.0

### PR DESCRIPTION
**Pull request by cubells**
Based in https://github.com/OCA/connector-woocommerce/pull/44

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What about the commit history?

**Comment by cubells** [comment]
The problem is that if I try to get commit history of this pr:

https://github.com/OCA/connector-woocommerce/pull/44/commits

I've got this:

**Comment by pedrobaeza** [comment]
Well, that means something incorrect in your git process. Remember to rebase your final work over current OCA branch.

**Comment by cubells** [comment]
Yes. Closed by https://github.com/OCA/connector-woocommerce/pull/50

**Pull request closed without merging**
