### PR TITLE
Add oca dependency for OCA/connector

### PR DESCRIPTION
**Pull request by rubencabrera**
Required repo to avoid ImportError when updating modules list. 
"Solves" #34

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @rubencabrera , travis and runbot must be green in order to review this PR. Could you check it please? Thanks!

**Comment by rubencabrera** [comment]
Hi, @rafaelbn 
The travis is failing for reasons not related to my PR. If this stays the same after I solve some urgent issues, I have no problem fixing it, but it's going to take a while, honestly.

**Comment by rafaelbn** [comment]
As I can see here: https://odoo-community.org/page/List the Team leader of this repo is @mathi123 ?

**Comment by mathi123** [comment]
That cant be right :)

**Pull request closed without merging**
